### ISSUE TITLE
Tweet Order

### ISSUE THREAD

**Issue by dataminer007** [kmacpher67/twitterpicyng#1]
Project Manager requested that tweets go out in a linear order, as of two months ago the tweet order was still "random". 

Project on hold:

**Comment by kmacpher67** [comment]
that's how the logic works. How do you envision "order" being established?
 based on relative or absolute DateTime or ordinal indexes?

**Comment by dataminer007** [comment]
Our competition uses drop down calendar menus to allow me to pick date and
time of a tweet if we say we are competing with Buffer and Hootsuite we had
better be able to do it, so I propose a fundamental shift in development.
We focus on the back end to drive this project.

**Comment by dataminer007** [comment]
Here is a google search of "open source social medial "open source social
network platform"

https://www.google.com/search?q=open+source+social+network+platform&rlz=1C1OPRB_enUS544US595&oq=open+source+social+&aqs=chrome.4.69i57j0l5.10844j0j7&sourceid=chrome&ie=UTF-8

And

"open source social network platform like facebook"

https://www.google.com/search?q=open+source+social+network+platform&rlz=1C1OPRB_enUS544US595&oq=open+source+social+&aqs=chrome.4.69i57j0l5.10844j0j7&sourceid=chrome&ie=UTF-8#q=open+source+social+network+platform+like+facebook

we take one and make it our version of Hootsuite and we go from there.

Got it dog

**Comment by dataminer007** [comment]
I will have to play with these as will you so we can pick the best on based
on use interface and codeability and how easy will it plug into twitterpic

**Comment by kmacpher67** [comment]
reading new scheduled only list.
